# Introduction {#sec:introduction}
The Atlantic Zone Monitoring Program (AZMP) was proposed in year 1998 [@therriault1998]. It identified sections of stations that would fulfill relevant objectives based on large scale physical and biological oceanographic processes for each region in the Atlantic region: Maritimes, Newfoundland and Labrador, Quebec, and Gulf. For the Maritimes region, four core transects of stations were proposed, Cabot Strait, Louisbourg, Halifax, and Cape Sable (later re-named Browns Bank, and will be used herein) (Figure \@ref(fig:mapOfAllStations)). Since the founding of the program, additional ancillary transects have been added to support various projects. These transects include St. Anns Bank, St. Pierre Bank, Laurentian Channel Mouth, The Gully, Sable Island Bank, LaHave Basin, Roseway Basin, Yarmouth, and Portsmouth (Figure \@ref(fig:mapOfAllStations)). Occupation of the core transects and various ancillary lines occurs bi-annually, during the spring, generally in the month of April, and in the fall, generally at the end of the month of September to mid October. <!--- , with the following monitoring objectives :

\begin{enumerate}
   \item{Cabot Strait}
   \begin{enumerate}
      \item{Assess the inflow and outflow of waters that connect the Gulf of St. Lawrence and Atlantic Ocean.}
   \end{enumerate}
   \item{Louisbourg}
   \begin{enumerate}
      \item{Assess the climate of the eastern Scotian Shelf.}
      \item{Estimate the inshore branch of the Nova Scotia current.}
      \item{Evaluate the influence of Labrador slope water and Gulf of St. Lawrence outflow on the outer shelf and upper slope.}
   \end{enumerate}
   \item{Halifax}
   \begin{enumerate}
      \item{Assess the climate of the central Scotian Shelf.}
      \item{Assess the climate of deep inner basins.}
      \item{Measure the strength of the Nova Scotia current.}
   \end{enumerate}
   \item{Browns Bank}
   \begin{enumerate}
      \item{Assess the climate of the western Scotian Shelf.}
      \item{Assess the inflow from the Bay of Fundy and Gulf of Maine.}
   \end{enumerate}
\end{enumerate}

In addition, others have been sampled since the founding of the program. These additional sections, which will be defined as ancillary, support the following needs :

\begin{enumerate}
   \item{Support monitoring initiatives by Oceans and Coastal Management Division.}
   \begin{enumerate}
      \item{St. Anns Bank}
      \item{The Gully}
   \end{enumerate}
   \item{Enhance understanding of hydrographic phenomena to support modeling efforts.}
   \begin{enumerate}
      \item{St. Pierre Bank}
      \item{Laurentian Channel Mouth}
      \item{LaHave Basin}
   \end{enumerate}
   \item{Fulfill a cooperative agreement with Northeastern Regional Association of Coastal Ocean Observing Systems (NERACOOS).}
   \begin{enumerate}
      \item{Yarmouth}
      \item{Portsmouth}
   \end{enumerate}
   \item{Support stakeholder (check this) projects.}
   \begin{enumerate}
      \item{Roseway Basin}
   \end{enumerate}
\end{enumerate}

The occupation of the ancillary sections has evolved and varied throughout the program. An evaluation of each ancillary will be completed to identify if a useful climatology can be developed.
-->

For monitoring efforts, the World Meteorological Organization (WMO) recommends using reference period of years 1961 to 1990 as well as the most recent three decades [@wmo2017]. Since the inception of the AZMP program was much later than the proposed reference period, available data within some reasonably defined area for each station is sparse. Therefore, calculations using the reference period for years 1961 to 1990 will not be considered. Instead, the two most recent overlapping three-decade periods, years 1981 to 2010 and years 1991 to 2020 will be presented as well as the differences between the two. When differences are presented, they are the 1991 to 2020 value minus the 1981 to 2010 value.