---
title: "Maritimes Region Atlantic Zone Monitoring Program 1991 to 2020 Hydrographic Transect Climatology"
french_title: "Maritimes Region Atlantic Zone Monitoring Program 1991 to 2020 Hydrographic Transect Climatology"
year: 2025
report_number: 229
author: |
  Chantelle Layton^1^
author_list: "Layton, C."
region: Maritimes Region
french_region: Région du Maritimes
isbn: "978-0-660-77722-1"
address: |
  ^1^Fisheries and Oceans Canada\
     Bedford Institute of Oceanography\
     P.O. Box 1006, 1 Challenger Drive\
     Dartmouth, Nova Scotia, B2Y 4A2\
french_address: |
  ^1^Pêches et Océans Canada\
     Division des sciences de l’océan et des écosystèmes\
     Institut océanographique de Bedford\
     Case postale 1006, 1, promenade Challenger\
     Dartmouth (Nouvelle-Écosse) B2Y 4A2\
phone: "(555) 555-5555"
author_footnote: "Email:Chantelle.Layton@dfo-mpo.gc.ca # | telephone: (250) 756-5555"
abstract: |
  The hydrographic 1991 to 2020 climatology for the Maritimes region Atlantic Zone Monitoring Program core transects, Cabot Strait, Louisbourg, Halifax, Browns Bank, and Northeast Channel, are calculated to support annual reporting on seasonal variability. Details on data coverage for these transects and ancillary transects occupied since the inception of the program are provided. Comparisons with the previous climatology period, years 1981 to 2010, are summarized when possible.
french_abstract: |
  La climatologie hydrographique de 1991 à 2020 pour les transects principaux du Programme de monitorage de la zone Atlantique dans la région des Maritimes : détroit de Cabot, Louisbourg, Halifax, banc Browns et chenal Nord-Est, est calculée afin d’appuyer la production de rapports annuels sur la variabilité saisonnière. Des détails sur la couverture des données pour ces transects et les transects annexes occupés depuis le début du programme sont fournis. Les comparaisons avec la période climatologique précédente, de 1981 à 2010, sont résumées dans la mesure du possible.
citation_french: "test"
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: false
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       bookdown::render_book("index.Rmd")
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "!ht"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```
